// Generated by `swift run GenerateTypedAlgebra`. Do not edit.

import Foundation

/// `UnitAcceleration` × `UnitDuration`, in the result type's base unit.
public func * (lhs: Measurement<UnitAcceleration>, rhs: Measurement<UnitDuration>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitAcceleration` ÷ `UnitFrequency`, in the result type's base unit.
public func / (lhs: Measurement<UnitAcceleration>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitAcceleration` ÷ `UnitSpeed`, in the result type's base unit.
public func / (lhs: Measurement<UnitAcceleration>, rhs: Measurement<UnitSpeed>) -> Measurement<UnitFrequency> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitFrequency.self)!
}

/// `UnitArea` × `UnitLength`, in the result type's base unit.
public func * (lhs: Measurement<UnitArea>, rhs: Measurement<UnitLength>) -> Measurement<UnitVolume> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitVolume.self)!
}

/// `UnitArea` ÷ `UnitLength`, in the result type's base unit.
public func / (lhs: Measurement<UnitArea>, rhs: Measurement<UnitLength>) -> Measurement<UnitLength> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitLength.self)!
}

/// `UnitConcentrationMass` × `UnitVolume`, in the result type's base unit.
public func * (lhs: Measurement<UnitConcentrationMass>, rhs: Measurement<UnitVolume>) -> Measurement<UnitMass> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitMass.self)!
}

/// `UnitDuration` × `UnitAcceleration`, in the result type's base unit.
public func * (lhs: Measurement<UnitDuration>, rhs: Measurement<UnitAcceleration>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitDuration` × `UnitElectricCurrent`, in the result type's base unit.
public func * (lhs: Measurement<UnitDuration>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitElectricCharge> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricCharge.self)!
}

/// `UnitDuration` × `UnitFrequency`, as a plain number.
public func * (lhs: Measurement<UnitDuration>, rhs: Measurement<UnitFrequency>) -> Double {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).value
}

/// `UnitDuration` × `UnitPower`, in the result type's base unit.
public func * (lhs: Measurement<UnitDuration>, rhs: Measurement<UnitPower>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitDuration` × `UnitSpeed`, in the result type's base unit.
public func * (lhs: Measurement<UnitDuration>, rhs: Measurement<UnitSpeed>) -> Measurement<UnitLength> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitLength.self)!
}

/// `UnitElectricCharge` ÷ `UnitDuration`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricCharge>, rhs: Measurement<UnitDuration>) -> Measurement<UnitElectricCurrent> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricCurrent.self)!
}

/// `UnitElectricCharge` ÷ `UnitElectricCurrent`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricCharge>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitDuration> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitDuration.self)!
}

/// `UnitElectricCharge` × `UnitElectricPotentialDifference`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricCharge>, rhs: Measurement<UnitElectricPotentialDifference>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitElectricCharge` × `UnitFrequency`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricCharge>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitElectricCurrent> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricCurrent.self)!
}

/// `UnitElectricCurrent` × `UnitDuration`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricCurrent>, rhs: Measurement<UnitDuration>) -> Measurement<UnitElectricCharge> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricCharge.self)!
}

/// `UnitElectricCurrent` ÷ `UnitElectricCharge`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricCurrent>, rhs: Measurement<UnitElectricCharge>) -> Measurement<UnitFrequency> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitFrequency.self)!
}

/// `UnitElectricCurrent` × `UnitElectricPotentialDifference`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricCurrent>, rhs: Measurement<UnitElectricPotentialDifference>) -> Measurement<UnitPower> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitPower.self)!
}

/// `UnitElectricCurrent` × `UnitElectricResistance`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricCurrent>, rhs: Measurement<UnitElectricResistance>) -> Measurement<UnitElectricPotentialDifference> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricPotentialDifference.self)!
}

/// `UnitElectricCurrent` ÷ `UnitFrequency`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricCurrent>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitElectricCharge> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricCharge.self)!
}

/// `UnitElectricPotentialDifference` × `UnitElectricCharge`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricPotentialDifference>, rhs: Measurement<UnitElectricCharge>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitElectricPotentialDifference` × `UnitElectricCurrent`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricPotentialDifference>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitPower> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitPower.self)!
}

/// `UnitElectricPotentialDifference` ÷ `UnitElectricCurrent`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricPotentialDifference>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitElectricResistance> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricResistance.self)!
}

/// `UnitElectricPotentialDifference` ÷ `UnitElectricResistance`, in the result type's base unit.
public func / (lhs: Measurement<UnitElectricPotentialDifference>, rhs: Measurement<UnitElectricResistance>) -> Measurement<UnitElectricCurrent> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricCurrent.self)!
}

/// `UnitElectricResistance` × `UnitElectricCurrent`, in the result type's base unit.
public func * (lhs: Measurement<UnitElectricResistance>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitElectricPotentialDifference> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricPotentialDifference.self)!
}

/// `UnitEnergy` ÷ `UnitDuration`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitDuration>) -> Measurement<UnitPower> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitPower.self)!
}

/// `UnitEnergy` ÷ `UnitElectricCharge`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitElectricCharge>) -> Measurement<UnitElectricPotentialDifference> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricPotentialDifference.self)!
}

/// `UnitEnergy` ÷ `UnitElectricPotentialDifference`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitElectricPotentialDifference>) -> Measurement<UnitElectricCharge> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricCharge.self)!
}

/// `UnitEnergy` × `UnitFrequency`, in the result type's base unit.
public func * (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitPower> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitPower.self)!
}

/// `UnitEnergy` ÷ `UnitPower`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitPower>) -> Measurement<UnitDuration> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitDuration.self)!
}

/// `UnitEnergy` ÷ `UnitPressure`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitPressure>) -> Measurement<UnitVolume> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitVolume.self)!
}

/// `UnitEnergy` ÷ `UnitVolume`, in the result type's base unit.
public func / (lhs: Measurement<UnitEnergy>, rhs: Measurement<UnitVolume>) -> Measurement<UnitPressure> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitPressure.self)!
}

/// `UnitFrequency` × `UnitDuration`, as a plain number.
public func * (lhs: Measurement<UnitFrequency>, rhs: Measurement<UnitDuration>) -> Double {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).value
}

/// `UnitFrequency` × `UnitElectricCharge`, in the result type's base unit.
public func * (lhs: Measurement<UnitFrequency>, rhs: Measurement<UnitElectricCharge>) -> Measurement<UnitElectricCurrent> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitElectricCurrent.self)!
}

/// `UnitFrequency` × `UnitEnergy`, in the result type's base unit.
public func * (lhs: Measurement<UnitFrequency>, rhs: Measurement<UnitEnergy>) -> Measurement<UnitPower> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitPower.self)!
}

/// `UnitFrequency` × `UnitLength`, in the result type's base unit.
public func * (lhs: Measurement<UnitFrequency>, rhs: Measurement<UnitLength>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitFrequency` × `UnitSpeed`, in the result type's base unit.
public func * (lhs: Measurement<UnitFrequency>, rhs: Measurement<UnitSpeed>) -> Measurement<UnitAcceleration> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitAcceleration.self)!
}

/// `UnitLength` × `UnitArea`, in the result type's base unit.
public func * (lhs: Measurement<UnitLength>, rhs: Measurement<UnitArea>) -> Measurement<UnitVolume> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitVolume.self)!
}

/// `UnitLength` ÷ `UnitDuration`, in the result type's base unit.
public func / (lhs: Measurement<UnitLength>, rhs: Measurement<UnitDuration>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitLength` × `UnitFrequency`, in the result type's base unit.
public func * (lhs: Measurement<UnitLength>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitSpeed> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitSpeed.self)!
}

/// `UnitLength` × `UnitLength`, in the result type's base unit.
public func * (lhs: Measurement<UnitLength>, rhs: Measurement<UnitLength>) -> Measurement<UnitArea> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitArea.self)!
}

/// `UnitLength` ÷ `UnitSpeed`, in the result type's base unit.
public func / (lhs: Measurement<UnitLength>, rhs: Measurement<UnitSpeed>) -> Measurement<UnitDuration> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitDuration.self)!
}

/// `UnitMass` ÷ `UnitConcentrationMass`, in the result type's base unit.
public func / (lhs: Measurement<UnitMass>, rhs: Measurement<UnitConcentrationMass>) -> Measurement<UnitVolume> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitVolume.self)!
}

/// `UnitMass` ÷ `UnitVolume`, in the result type's base unit.
public func / (lhs: Measurement<UnitMass>, rhs: Measurement<UnitVolume>) -> Measurement<UnitConcentrationMass> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitConcentrationMass.self)!
}

/// `UnitPower` × `UnitDuration`, in the result type's base unit.
public func * (lhs: Measurement<UnitPower>, rhs: Measurement<UnitDuration>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitPower` ÷ `UnitElectricCurrent`, in the result type's base unit.
public func / (lhs: Measurement<UnitPower>, rhs: Measurement<UnitElectricCurrent>) -> Measurement<UnitElectricPotentialDifference> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricPotentialDifference.self)!
}

/// `UnitPower` ÷ `UnitElectricPotentialDifference`, in the result type's base unit.
public func / (lhs: Measurement<UnitPower>, rhs: Measurement<UnitElectricPotentialDifference>) -> Measurement<UnitElectricCurrent> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitElectricCurrent.self)!
}

/// `UnitPower` ÷ `UnitEnergy`, in the result type's base unit.
public func / (lhs: Measurement<UnitPower>, rhs: Measurement<UnitEnergy>) -> Measurement<UnitFrequency> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitFrequency.self)!
}

/// `UnitPower` ÷ `UnitFrequency`, in the result type's base unit.
public func / (lhs: Measurement<UnitPower>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitPressure` × `UnitVolume`, in the result type's base unit.
public func * (lhs: Measurement<UnitPressure>, rhs: Measurement<UnitVolume>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}

/// `UnitSpeed` ÷ `UnitAcceleration`, in the result type's base unit.
public func / (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitAcceleration>) -> Measurement<UnitDuration> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitDuration.self)!
}

/// `UnitSpeed` × `UnitDuration`, in the result type's base unit.
public func * (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitDuration>) -> Measurement<UnitLength> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitLength.self)!
}

/// `UnitSpeed` ÷ `UnitDuration`, in the result type's base unit.
public func / (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitDuration>) -> Measurement<UnitAcceleration> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitAcceleration.self)!
}

/// `UnitSpeed` × `UnitFrequency`, in the result type's base unit.
public func * (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitAcceleration> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitAcceleration.self)!
}

/// `UnitSpeed` ÷ `UnitFrequency`, in the result type's base unit.
public func / (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitFrequency>) -> Measurement<UnitLength> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitLength.self)!
}

/// `UnitSpeed` ÷ `UnitLength`, in the result type's base unit.
public func / (lhs: Measurement<UnitSpeed>, rhs: Measurement<UnitLength>) -> Measurement<UnitFrequency> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitFrequency.self)!
}

/// `UnitVolume` ÷ `UnitArea`, in the result type's base unit.
public func / (lhs: Measurement<UnitVolume>, rhs: Measurement<UnitArea>) -> Measurement<UnitLength> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitLength.self)!
}

/// `UnitVolume` × `UnitConcentrationMass`, in the result type's base unit.
public func * (lhs: Measurement<UnitVolume>, rhs: Measurement<UnitConcentrationMass>) -> Measurement<UnitMass> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitMass.self)!
}

/// `UnitVolume` ÷ `UnitLength`, in the result type's base unit.
public func / (lhs: Measurement<UnitVolume>, rhs: Measurement<UnitLength>) -> Measurement<UnitArea> {
    (DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)).convert(to: UnitArea.self)!
}

/// `UnitVolume` × `UnitPressure`, in the result type's base unit.
public func * (lhs: Measurement<UnitVolume>, rhs: Measurement<UnitPressure>) -> Measurement<UnitEnergy> {
    (DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)).convert(to: UnitEnergy.self)!
}
