// Generated by `swift run GenerateTypedAlgebra`. Do not edit.

import Foundation
import Testing
@testable import SwiftMeasurement

@Suite("Typed Algebra (generated)")
struct TypedAlgebraGeneratedTests {

    @Test("Every typed operator agrees with DimensionalMeasurement")
    func agreement() {
        do {
            let lhs = Measurement(value: 3.0, unit: UnitAcceleration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitAcceleration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitAcceleration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitSpeed.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitFrequency> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitArea.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitVolume> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitArea.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitLength> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitConcentrationMass.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitVolume.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitMass> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitDuration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitAcceleration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitDuration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCharge> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitDuration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Double = lhs * rhs
            #expect(abs(typed - expected.value) < 1e-9)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitDuration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitPower.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitDuration.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitSpeed.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitLength> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCharge.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCurrent> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCharge.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitDuration> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCharge.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricPotentialDifference.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCharge.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCurrent> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCurrent.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCharge> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCurrent.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCharge.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitFrequency> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCurrent.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricPotentialDifference.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPower> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCurrent.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricResistance.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricPotentialDifference> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricCurrent.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCharge> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricPotentialDifference.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCharge.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricPotentialDifference.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPower> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricPotentialDifference.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricResistance> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricPotentialDifference.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricResistance.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCurrent> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitElectricResistance.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricPotentialDifference> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPower> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCharge.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricPotentialDifference> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricPotentialDifference.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCharge> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPower> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitPower.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitDuration> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitPressure.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitVolume> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitEnergy.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitVolume.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPressure> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitFrequency.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Double = lhs * rhs
            #expect(abs(typed - expected.value) < 1e-9)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitFrequency.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCharge.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCurrent> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitFrequency.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitEnergy.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitPower> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitFrequency.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitFrequency.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitSpeed.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitAcceleration> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitLength.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitArea.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitVolume> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitLength.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitLength.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitSpeed> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitLength.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitArea> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitLength.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitSpeed.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitDuration> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitMass.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitConcentrationMass.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitVolume> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitMass.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitVolume.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitConcentrationMass> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPower.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPower.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricCurrent.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricPotentialDifference> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPower.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitElectricPotentialDifference.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitElectricCurrent> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPower.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitEnergy.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitFrequency> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPower.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitPressure.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitVolume.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitAcceleration.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitDuration> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitLength> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitDuration.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitAcceleration> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitAcceleration> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitFrequency.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitLength> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitSpeed.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitFrequency> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitVolume.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitArea.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitLength> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitVolume.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitConcentrationMass.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitMass> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitVolume.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitLength.baseUnit())
            let expected = DimensionalMeasurement(lhs) / DimensionalMeasurement(rhs)
            let typed: Measurement<UnitArea> = lhs / rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

        do {
            let lhs = Measurement(value: 3.0, unit: UnitVolume.baseUnit())
            let rhs = Measurement(value: 2.0, unit: UnitPressure.baseUnit())
            let expected = DimensionalMeasurement(lhs) * DimensionalMeasurement(rhs)
            let typed: Measurement<UnitEnergy> = lhs * rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }
    }
}
