// Prints one deterministic line per Foundation unit behaviour, so the output of two platforms can be diffed.
import Foundation

let encodesNonLinear = false  // encoding a non-linear converter traps on every platform

setvbuf(stdout, nil, _IONBF, 0)
func out(_ k: String, _ v: Any) { print("\(k)\t\(v)") }
func convName(_ c: UnitConverter) -> String {
    if let l = c as? UnitConverterLinear { return "linear(\(l.coefficient),\(l.constant))" }
    let n = String(describing: type(of: c))
    return n.contains("Reciprocal") ? "reciprocal" : n
}
func json<T: Encodable>(_ v: T) -> String {
    let e = JSONEncoder(); e.outputFormatting = [.sortedKeys]
    do { return String(data: try e.encode(v), encoding: .utf8)! } catch { return "ENCODE-ERROR" }
}
func probe<T: Dimension>(_ k: String, _ u: T, _ fresh: T) {
    let base = T.baseUnit()
    out("\(k).symbol", u.symbol)
    out("\(k).converter", convName(u.converter))
    let m = Measurement(value: 1, unit: u)
    out("\(k).toBase(1)", m.converted(to: base).value)
    out("\(k).fromBase(1)", Measurement(value: 1, unit: base).converted(to: u).value)
    out("\(k).unit==fresh", u == fresh)
    out("\(k).unit.hash==fresh.hash", u.hash == fresh.hash)
    out("\(k).set(u,fresh).count", Set([u, fresh]).count)
    let mb = m.converted(to: base)
    out("\(k).m==m.toBase", m == mb)
    out("\(k).m.hash==m.toBase.hash", m.hashValue == mb.hashValue)
    out("\(k).description", "\(Measurement(value: 1.5, unit: u))")
    let linear = u.converter is UnitConverterLinear
    if linear || encodesNonLinear {
        let j = json(m)
        out("\(k).json", j)
        if let back = try? JSONDecoder().decode(Measurement<T>.self, from: Data(j.utf8)) {
            out("\(k).json.roundtrip", "equal=\(back == m) unitEqual=\(back.unit == u) toBase=\(back.converted(to: base).value)")
        } else { out("\(k).json.roundtrip", "DECODE-ERROR") }
    } else { out("\(k).json", "TRAPS(non-linear converter)") }
    do {
        let data = try NSKeyedArchiver.archivedData(withRootObject: u, requiringSecureCoding: true)
        let back = try NSKeyedUnarchiver.unarchivedObject(ofClass: T.self, from: data)
        out("\(k).archive.roundtrip", back.map { "equal=\($0 == u) converter=\(convName($0.converter))" } ?? "nil")
    } catch { out("\(k).archive.roundtrip", "ERROR") }
}
func probeType<T: Dimension>(_ k: String, _ t: T.Type, _ a: T, _ b: T) {
    out("\(k).baseUnit", T.baseUnit().symbol)
    out("\(k).baseUnit.converter", convName(T.baseUnit().converter))
    let custom = T(symbol: "x", converter: UnitConverterLinear(coefficient: 2))
    out("\(k).custom.type", String(describing: type(of: custom)))
    out("\(k).custom.toBase(3)", Measurement(value: 3, unit: custom).converted(to: T.baseUnit()).value)
    let ma = Measurement(value: 1, unit: a), mb = Measurement(value: 1, unit: b)
    let sum = ma + mb, diff = ma - mb
    out("\(k).a+b", "\(sum.value) \(sum.unit.symbol)")
    out("\(k).a-b", "\(diff.value) \(diff.unit.symbol)")
    out("\(k).a<b", ma < mb)
    out("\(k).a+a", "\((ma + ma).value) \((ma + ma).unit.symbol)")
    let ns = NSMeasurement(doubleValue: 1, unit: a)
    out("\(k).ns.canBeConverted", ns.canBeConverted(to: b))
    out("\(k).ns.converting", ns.converting(to: b).value)
    #if canImport(Darwin)
    if k == "UnitFuelEfficiency" { out("\(k).ns.adding", "RAISES NSInvalidArgumentException") } else { out("\(k).ns.adding", ns.adding(Measurement(value: 1, unit: b as Unit)).value) }
    #else
    out("\(k).ns.adding", ns.adding(Measurement(value: 1, unit: b as Unit)).value)
    #endif
    out("\(k).ns.isEqual", ns.isEqual(NSMeasurement(doubleValue: 1, unit: a)))
    out("\(k).ns.hash==", ns.hash == NSMeasurement(doubleValue: 1, unit: a).hash)
}

probe("UnitAcceleration.metersPerSecondSquared", UnitAcceleration.metersPerSecondSquared, UnitAcceleration.metersPerSecondSquared)
probe("UnitAcceleration.gravity", UnitAcceleration.gravity, UnitAcceleration.gravity)
probeType("UnitAcceleration", UnitAcceleration.self, UnitAcceleration.metersPerSecondSquared, UnitAcceleration.gravity)
probe("UnitAngle.degrees", UnitAngle.degrees, UnitAngle.degrees)
probe("UnitAngle.arcMinutes", UnitAngle.arcMinutes, UnitAngle.arcMinutes)
probe("UnitAngle.arcSeconds", UnitAngle.arcSeconds, UnitAngle.arcSeconds)
probe("UnitAngle.radians", UnitAngle.radians, UnitAngle.radians)
probe("UnitAngle.gradians", UnitAngle.gradians, UnitAngle.gradians)
probe("UnitAngle.revolutions", UnitAngle.revolutions, UnitAngle.revolutions)
probeType("UnitAngle", UnitAngle.self, UnitAngle.degrees, UnitAngle.revolutions)
probe("UnitArea.squareMegameters", UnitArea.squareMegameters, UnitArea.squareMegameters)
probe("UnitArea.squareKilometers", UnitArea.squareKilometers, UnitArea.squareKilometers)
probe("UnitArea.squareMeters", UnitArea.squareMeters, UnitArea.squareMeters)
probe("UnitArea.squareCentimeters", UnitArea.squareCentimeters, UnitArea.squareCentimeters)
probe("UnitArea.squareMillimeters", UnitArea.squareMillimeters, UnitArea.squareMillimeters)
probe("UnitArea.squareMicrometers", UnitArea.squareMicrometers, UnitArea.squareMicrometers)
probe("UnitArea.squareNanometers", UnitArea.squareNanometers, UnitArea.squareNanometers)
probe("UnitArea.squareInches", UnitArea.squareInches, UnitArea.squareInches)
probe("UnitArea.squareFeet", UnitArea.squareFeet, UnitArea.squareFeet)
probe("UnitArea.squareYards", UnitArea.squareYards, UnitArea.squareYards)
probe("UnitArea.squareMiles", UnitArea.squareMiles, UnitArea.squareMiles)
probe("UnitArea.acres", UnitArea.acres, UnitArea.acres)
probe("UnitArea.ares", UnitArea.ares, UnitArea.ares)
probe("UnitArea.hectares", UnitArea.hectares, UnitArea.hectares)
probeType("UnitArea", UnitArea.self, UnitArea.squareMegameters, UnitArea.hectares)
probe("UnitConcentrationMass.gramsPerLiter", UnitConcentrationMass.gramsPerLiter, UnitConcentrationMass.gramsPerLiter)
probe("UnitConcentrationMass.milligramsPerDeciliter", UnitConcentrationMass.milligramsPerDeciliter, UnitConcentrationMass.milligramsPerDeciliter)
probeType("UnitConcentrationMass", UnitConcentrationMass.self, UnitConcentrationMass.gramsPerLiter, UnitConcentrationMass.milligramsPerDeciliter)
probe("UnitDispersion.partsPerMillion", UnitDispersion.partsPerMillion, UnitDispersion.partsPerMillion)
probeType("UnitDispersion", UnitDispersion.self, UnitDispersion.partsPerMillion, UnitDispersion.partsPerMillion)
probe("UnitDuration.picoseconds", UnitDuration.picoseconds, UnitDuration.picoseconds)
probe("UnitDuration.nanoseconds", UnitDuration.nanoseconds, UnitDuration.nanoseconds)
probe("UnitDuration.microseconds", UnitDuration.microseconds, UnitDuration.microseconds)
probe("UnitDuration.milliseconds", UnitDuration.milliseconds, UnitDuration.milliseconds)
probe("UnitDuration.seconds", UnitDuration.seconds, UnitDuration.seconds)
probe("UnitDuration.minutes", UnitDuration.minutes, UnitDuration.minutes)
probe("UnitDuration.hours", UnitDuration.hours, UnitDuration.hours)
probeType("UnitDuration", UnitDuration.self, UnitDuration.picoseconds, UnitDuration.hours)
probe("UnitElectricCharge.coulombs", UnitElectricCharge.coulombs, UnitElectricCharge.coulombs)
probe("UnitElectricCharge.megaampereHours", UnitElectricCharge.megaampereHours, UnitElectricCharge.megaampereHours)
probe("UnitElectricCharge.kiloampereHours", UnitElectricCharge.kiloampereHours, UnitElectricCharge.kiloampereHours)
probe("UnitElectricCharge.ampereHours", UnitElectricCharge.ampereHours, UnitElectricCharge.ampereHours)
probe("UnitElectricCharge.milliampereHours", UnitElectricCharge.milliampereHours, UnitElectricCharge.milliampereHours)
probe("UnitElectricCharge.microampereHours", UnitElectricCharge.microampereHours, UnitElectricCharge.microampereHours)
probeType("UnitElectricCharge", UnitElectricCharge.self, UnitElectricCharge.coulombs, UnitElectricCharge.microampereHours)
probe("UnitElectricCurrent.megaamperes", UnitElectricCurrent.megaamperes, UnitElectricCurrent.megaamperes)
probe("UnitElectricCurrent.kiloamperes", UnitElectricCurrent.kiloamperes, UnitElectricCurrent.kiloamperes)
probe("UnitElectricCurrent.amperes", UnitElectricCurrent.amperes, UnitElectricCurrent.amperes)
probe("UnitElectricCurrent.milliamperes", UnitElectricCurrent.milliamperes, UnitElectricCurrent.milliamperes)
probe("UnitElectricCurrent.microamperes", UnitElectricCurrent.microamperes, UnitElectricCurrent.microamperes)
probeType("UnitElectricCurrent", UnitElectricCurrent.self, UnitElectricCurrent.megaamperes, UnitElectricCurrent.microamperes)
probe("UnitElectricPotentialDifference.megavolts", UnitElectricPotentialDifference.megavolts, UnitElectricPotentialDifference.megavolts)
probe("UnitElectricPotentialDifference.kilovolts", UnitElectricPotentialDifference.kilovolts, UnitElectricPotentialDifference.kilovolts)
probe("UnitElectricPotentialDifference.volts", UnitElectricPotentialDifference.volts, UnitElectricPotentialDifference.volts)
probe("UnitElectricPotentialDifference.millivolts", UnitElectricPotentialDifference.millivolts, UnitElectricPotentialDifference.millivolts)
probe("UnitElectricPotentialDifference.microvolts", UnitElectricPotentialDifference.microvolts, UnitElectricPotentialDifference.microvolts)
probeType("UnitElectricPotentialDifference", UnitElectricPotentialDifference.self, UnitElectricPotentialDifference.megavolts, UnitElectricPotentialDifference.microvolts)
probe("UnitElectricResistance.megaohms", UnitElectricResistance.megaohms, UnitElectricResistance.megaohms)
probe("UnitElectricResistance.kiloohms", UnitElectricResistance.kiloohms, UnitElectricResistance.kiloohms)
probe("UnitElectricResistance.ohms", UnitElectricResistance.ohms, UnitElectricResistance.ohms)
probe("UnitElectricResistance.milliohms", UnitElectricResistance.milliohms, UnitElectricResistance.milliohms)
probe("UnitElectricResistance.microohms", UnitElectricResistance.microohms, UnitElectricResistance.microohms)
probeType("UnitElectricResistance", UnitElectricResistance.self, UnitElectricResistance.megaohms, UnitElectricResistance.microohms)
probe("UnitEnergy.kilojoules", UnitEnergy.kilojoules, UnitEnergy.kilojoules)
probe("UnitEnergy.joules", UnitEnergy.joules, UnitEnergy.joules)
probe("UnitEnergy.kilocalories", UnitEnergy.kilocalories, UnitEnergy.kilocalories)
probe("UnitEnergy.calories", UnitEnergy.calories, UnitEnergy.calories)
probe("UnitEnergy.kilowattHours", UnitEnergy.kilowattHours, UnitEnergy.kilowattHours)
probeType("UnitEnergy", UnitEnergy.self, UnitEnergy.kilojoules, UnitEnergy.kilowattHours)
probe("UnitFrequency.terahertz", UnitFrequency.terahertz, UnitFrequency.terahertz)
probe("UnitFrequency.gigahertz", UnitFrequency.gigahertz, UnitFrequency.gigahertz)
probe("UnitFrequency.megahertz", UnitFrequency.megahertz, UnitFrequency.megahertz)
probe("UnitFrequency.kilohertz", UnitFrequency.kilohertz, UnitFrequency.kilohertz)
probe("UnitFrequency.hertz", UnitFrequency.hertz, UnitFrequency.hertz)
probe("UnitFrequency.millihertz", UnitFrequency.millihertz, UnitFrequency.millihertz)
probe("UnitFrequency.microhertz", UnitFrequency.microhertz, UnitFrequency.microhertz)
probe("UnitFrequency.nanohertz", UnitFrequency.nanohertz, UnitFrequency.nanohertz)
#if canImport(Darwin) || compiler(>=6.4)
probe("UnitFrequency.framesPerSecond", UnitFrequency.framesPerSecond, UnitFrequency.framesPerSecond)
#endif
probeType("UnitFrequency", UnitFrequency.self, UnitFrequency.terahertz, UnitFrequency.framesPerSecond)
probe("UnitFuelEfficiency.litersPer100Kilometers", UnitFuelEfficiency.litersPer100Kilometers, UnitFuelEfficiency.litersPer100Kilometers)
probe("UnitFuelEfficiency.milesPerImperialGallon", UnitFuelEfficiency.milesPerImperialGallon, UnitFuelEfficiency.milesPerImperialGallon)
probe("UnitFuelEfficiency.milesPerGallon", UnitFuelEfficiency.milesPerGallon, UnitFuelEfficiency.milesPerGallon)
probeType("UnitFuelEfficiency", UnitFuelEfficiency.self, UnitFuelEfficiency.litersPer100Kilometers, UnitFuelEfficiency.milesPerGallon)
probe("UnitLength.megameters", UnitLength.megameters, UnitLength.megameters)
probe("UnitLength.kilometers", UnitLength.kilometers, UnitLength.kilometers)
probe("UnitLength.hectometers", UnitLength.hectometers, UnitLength.hectometers)
probe("UnitLength.decameters", UnitLength.decameters, UnitLength.decameters)
probe("UnitLength.meters", UnitLength.meters, UnitLength.meters)
probe("UnitLength.decimeters", UnitLength.decimeters, UnitLength.decimeters)
probe("UnitLength.centimeters", UnitLength.centimeters, UnitLength.centimeters)
probe("UnitLength.millimeters", UnitLength.millimeters, UnitLength.millimeters)
probe("UnitLength.micrometers", UnitLength.micrometers, UnitLength.micrometers)
probe("UnitLength.nanometers", UnitLength.nanometers, UnitLength.nanometers)
probe("UnitLength.picometers", UnitLength.picometers, UnitLength.picometers)
probe("UnitLength.inches", UnitLength.inches, UnitLength.inches)
probe("UnitLength.feet", UnitLength.feet, UnitLength.feet)
probe("UnitLength.yards", UnitLength.yards, UnitLength.yards)
probe("UnitLength.miles", UnitLength.miles, UnitLength.miles)
probe("UnitLength.scandinavianMiles", UnitLength.scandinavianMiles, UnitLength.scandinavianMiles)
probe("UnitLength.lightyears", UnitLength.lightyears, UnitLength.lightyears)
probe("UnitLength.nauticalMiles", UnitLength.nauticalMiles, UnitLength.nauticalMiles)
probe("UnitLength.fathoms", UnitLength.fathoms, UnitLength.fathoms)
probe("UnitLength.furlongs", UnitLength.furlongs, UnitLength.furlongs)
probe("UnitLength.astronomicalUnits", UnitLength.astronomicalUnits, UnitLength.astronomicalUnits)
probe("UnitLength.parsecs", UnitLength.parsecs, UnitLength.parsecs)
probeType("UnitLength", UnitLength.self, UnitLength.megameters, UnitLength.parsecs)
probe("UnitIlluminance.lux", UnitIlluminance.lux, UnitIlluminance.lux)
probeType("UnitIlluminance", UnitIlluminance.self, UnitIlluminance.lux, UnitIlluminance.lux)
probe("UnitInformationStorage.bytes", UnitInformationStorage.bytes, UnitInformationStorage.bytes)
probe("UnitInformationStorage.bits", UnitInformationStorage.bits, UnitInformationStorage.bits)
probe("UnitInformationStorage.nibbles", UnitInformationStorage.nibbles, UnitInformationStorage.nibbles)
probe("UnitInformationStorage.yottabytes", UnitInformationStorage.yottabytes, UnitInformationStorage.yottabytes)
probe("UnitInformationStorage.zettabytes", UnitInformationStorage.zettabytes, UnitInformationStorage.zettabytes)
probe("UnitInformationStorage.exabytes", UnitInformationStorage.exabytes, UnitInformationStorage.exabytes)
probe("UnitInformationStorage.petabytes", UnitInformationStorage.petabytes, UnitInformationStorage.petabytes)
probe("UnitInformationStorage.terabytes", UnitInformationStorage.terabytes, UnitInformationStorage.terabytes)
probe("UnitInformationStorage.gigabytes", UnitInformationStorage.gigabytes, UnitInformationStorage.gigabytes)
probe("UnitInformationStorage.megabytes", UnitInformationStorage.megabytes, UnitInformationStorage.megabytes)
probe("UnitInformationStorage.kilobytes", UnitInformationStorage.kilobytes, UnitInformationStorage.kilobytes)
probe("UnitInformationStorage.yottabits", UnitInformationStorage.yottabits, UnitInformationStorage.yottabits)
probe("UnitInformationStorage.zettabits", UnitInformationStorage.zettabits, UnitInformationStorage.zettabits)
probe("UnitInformationStorage.exabits", UnitInformationStorage.exabits, UnitInformationStorage.exabits)
probe("UnitInformationStorage.petabits", UnitInformationStorage.petabits, UnitInformationStorage.petabits)
probe("UnitInformationStorage.terabits", UnitInformationStorage.terabits, UnitInformationStorage.terabits)
probe("UnitInformationStorage.gigabits", UnitInformationStorage.gigabits, UnitInformationStorage.gigabits)
probe("UnitInformationStorage.megabits", UnitInformationStorage.megabits, UnitInformationStorage.megabits)
probe("UnitInformationStorage.kilobits", UnitInformationStorage.kilobits, UnitInformationStorage.kilobits)
probe("UnitInformationStorage.yobibytes", UnitInformationStorage.yobibytes, UnitInformationStorage.yobibytes)
probe("UnitInformationStorage.zebibytes", UnitInformationStorage.zebibytes, UnitInformationStorage.zebibytes)
probe("UnitInformationStorage.exbibytes", UnitInformationStorage.exbibytes, UnitInformationStorage.exbibytes)
probe("UnitInformationStorage.pebibytes", UnitInformationStorage.pebibytes, UnitInformationStorage.pebibytes)
probe("UnitInformationStorage.tebibytes", UnitInformationStorage.tebibytes, UnitInformationStorage.tebibytes)
probe("UnitInformationStorage.gibibytes", UnitInformationStorage.gibibytes, UnitInformationStorage.gibibytes)
probe("UnitInformationStorage.mebibytes", UnitInformationStorage.mebibytes, UnitInformationStorage.mebibytes)
probe("UnitInformationStorage.kibibytes", UnitInformationStorage.kibibytes, UnitInformationStorage.kibibytes)
probe("UnitInformationStorage.yobibits", UnitInformationStorage.yobibits, UnitInformationStorage.yobibits)
probe("UnitInformationStorage.zebibits", UnitInformationStorage.zebibits, UnitInformationStorage.zebibits)
probe("UnitInformationStorage.exbibits", UnitInformationStorage.exbibits, UnitInformationStorage.exbibits)
probe("UnitInformationStorage.pebibits", UnitInformationStorage.pebibits, UnitInformationStorage.pebibits)
probe("UnitInformationStorage.tebibits", UnitInformationStorage.tebibits, UnitInformationStorage.tebibits)
probe("UnitInformationStorage.gibibits", UnitInformationStorage.gibibits, UnitInformationStorage.gibibits)
probe("UnitInformationStorage.mebibits", UnitInformationStorage.mebibits, UnitInformationStorage.mebibits)
probe("UnitInformationStorage.kibibits", UnitInformationStorage.kibibits, UnitInformationStorage.kibibits)
probeType("UnitInformationStorage", UnitInformationStorage.self, UnitInformationStorage.bytes, UnitInformationStorage.kibibits)
probe("UnitMass.kilograms", UnitMass.kilograms, UnitMass.kilograms)
probe("UnitMass.grams", UnitMass.grams, UnitMass.grams)
probe("UnitMass.decigrams", UnitMass.decigrams, UnitMass.decigrams)
probe("UnitMass.centigrams", UnitMass.centigrams, UnitMass.centigrams)
probe("UnitMass.milligrams", UnitMass.milligrams, UnitMass.milligrams)
probe("UnitMass.micrograms", UnitMass.micrograms, UnitMass.micrograms)
probe("UnitMass.nanograms", UnitMass.nanograms, UnitMass.nanograms)
probe("UnitMass.picograms", UnitMass.picograms, UnitMass.picograms)
probe("UnitMass.ounces", UnitMass.ounces, UnitMass.ounces)
probe("UnitMass.pounds", UnitMass.pounds, UnitMass.pounds)
probe("UnitMass.stones", UnitMass.stones, UnitMass.stones)
probe("UnitMass.metricTons", UnitMass.metricTons, UnitMass.metricTons)
probe("UnitMass.shortTons", UnitMass.shortTons, UnitMass.shortTons)
probe("UnitMass.carats", UnitMass.carats, UnitMass.carats)
probe("UnitMass.ouncesTroy", UnitMass.ouncesTroy, UnitMass.ouncesTroy)
probe("UnitMass.slugs", UnitMass.slugs, UnitMass.slugs)
probeType("UnitMass", UnitMass.self, UnitMass.kilograms, UnitMass.slugs)
probe("UnitPower.terawatts", UnitPower.terawatts, UnitPower.terawatts)
probe("UnitPower.gigawatts", UnitPower.gigawatts, UnitPower.gigawatts)
probe("UnitPower.megawatts", UnitPower.megawatts, UnitPower.megawatts)
probe("UnitPower.kilowatts", UnitPower.kilowatts, UnitPower.kilowatts)
probe("UnitPower.watts", UnitPower.watts, UnitPower.watts)
probe("UnitPower.milliwatts", UnitPower.milliwatts, UnitPower.milliwatts)
probe("UnitPower.microwatts", UnitPower.microwatts, UnitPower.microwatts)
probe("UnitPower.nanowatts", UnitPower.nanowatts, UnitPower.nanowatts)
probe("UnitPower.picowatts", UnitPower.picowatts, UnitPower.picowatts)
probe("UnitPower.femtowatts", UnitPower.femtowatts, UnitPower.femtowatts)
probe("UnitPower.horsepower", UnitPower.horsepower, UnitPower.horsepower)
probeType("UnitPower", UnitPower.self, UnitPower.terawatts, UnitPower.horsepower)
probe("UnitPressure.newtonsPerMetersSquared", UnitPressure.newtonsPerMetersSquared, UnitPressure.newtonsPerMetersSquared)
probe("UnitPressure.gigapascals", UnitPressure.gigapascals, UnitPressure.gigapascals)
probe("UnitPressure.megapascals", UnitPressure.megapascals, UnitPressure.megapascals)
probe("UnitPressure.kilopascals", UnitPressure.kilopascals, UnitPressure.kilopascals)
probe("UnitPressure.hectopascals", UnitPressure.hectopascals, UnitPressure.hectopascals)
probe("UnitPressure.inchesOfMercury", UnitPressure.inchesOfMercury, UnitPressure.inchesOfMercury)
probe("UnitPressure.bars", UnitPressure.bars, UnitPressure.bars)
probe("UnitPressure.millibars", UnitPressure.millibars, UnitPressure.millibars)
probe("UnitPressure.millimetersOfMercury", UnitPressure.millimetersOfMercury, UnitPressure.millimetersOfMercury)
probe("UnitPressure.poundsForcePerSquareInch", UnitPressure.poundsForcePerSquareInch, UnitPressure.poundsForcePerSquareInch)
probeType("UnitPressure", UnitPressure.self, UnitPressure.newtonsPerMetersSquared, UnitPressure.poundsForcePerSquareInch)
probe("UnitSpeed.metersPerSecond", UnitSpeed.metersPerSecond, UnitSpeed.metersPerSecond)
probe("UnitSpeed.kilometersPerHour", UnitSpeed.kilometersPerHour, UnitSpeed.kilometersPerHour)
probe("UnitSpeed.milesPerHour", UnitSpeed.milesPerHour, UnitSpeed.milesPerHour)
probe("UnitSpeed.knots", UnitSpeed.knots, UnitSpeed.knots)
probeType("UnitSpeed", UnitSpeed.self, UnitSpeed.metersPerSecond, UnitSpeed.knots)
probe("UnitTemperature.kelvin", UnitTemperature.kelvin, UnitTemperature.kelvin)
probe("UnitTemperature.celsius", UnitTemperature.celsius, UnitTemperature.celsius)
probe("UnitTemperature.fahrenheit", UnitTemperature.fahrenheit, UnitTemperature.fahrenheit)
probeType("UnitTemperature", UnitTemperature.self, UnitTemperature.kelvin, UnitTemperature.fahrenheit)
probe("UnitVolume.megaliters", UnitVolume.megaliters, UnitVolume.megaliters)
probe("UnitVolume.kiloliters", UnitVolume.kiloliters, UnitVolume.kiloliters)
probe("UnitVolume.liters", UnitVolume.liters, UnitVolume.liters)
probe("UnitVolume.deciliters", UnitVolume.deciliters, UnitVolume.deciliters)
probe("UnitVolume.centiliters", UnitVolume.centiliters, UnitVolume.centiliters)
probe("UnitVolume.milliliters", UnitVolume.milliliters, UnitVolume.milliliters)
probe("UnitVolume.cubicKilometers", UnitVolume.cubicKilometers, UnitVolume.cubicKilometers)
probe("UnitVolume.cubicMeters", UnitVolume.cubicMeters, UnitVolume.cubicMeters)
probe("UnitVolume.cubicDecimeters", UnitVolume.cubicDecimeters, UnitVolume.cubicDecimeters)
probe("UnitVolume.cubicCentimeters", UnitVolume.cubicCentimeters, UnitVolume.cubicCentimeters)
probe("UnitVolume.cubicMillimeters", UnitVolume.cubicMillimeters, UnitVolume.cubicMillimeters)
probe("UnitVolume.cubicInches", UnitVolume.cubicInches, UnitVolume.cubicInches)
probe("UnitVolume.cubicFeet", UnitVolume.cubicFeet, UnitVolume.cubicFeet)
probe("UnitVolume.cubicYards", UnitVolume.cubicYards, UnitVolume.cubicYards)
probe("UnitVolume.cubicMiles", UnitVolume.cubicMiles, UnitVolume.cubicMiles)
probe("UnitVolume.acreFeet", UnitVolume.acreFeet, UnitVolume.acreFeet)
probe("UnitVolume.bushels", UnitVolume.bushels, UnitVolume.bushels)
probe("UnitVolume.teaspoons", UnitVolume.teaspoons, UnitVolume.teaspoons)
probe("UnitVolume.tablespoons", UnitVolume.tablespoons, UnitVolume.tablespoons)
probe("UnitVolume.fluidOunces", UnitVolume.fluidOunces, UnitVolume.fluidOunces)
probe("UnitVolume.cups", UnitVolume.cups, UnitVolume.cups)
probe("UnitVolume.pints", UnitVolume.pints, UnitVolume.pints)
probe("UnitVolume.quarts", UnitVolume.quarts, UnitVolume.quarts)
probe("UnitVolume.gallons", UnitVolume.gallons, UnitVolume.gallons)
probe("UnitVolume.imperialTeaspoons", UnitVolume.imperialTeaspoons, UnitVolume.imperialTeaspoons)
probe("UnitVolume.imperialTablespoons", UnitVolume.imperialTablespoons, UnitVolume.imperialTablespoons)
probe("UnitVolume.imperialFluidOunces", UnitVolume.imperialFluidOunces, UnitVolume.imperialFluidOunces)
probe("UnitVolume.imperialPints", UnitVolume.imperialPints, UnitVolume.imperialPints)
probe("UnitVolume.imperialQuarts", UnitVolume.imperialQuarts, UnitVolume.imperialQuarts)
probe("UnitVolume.imperialGallons", UnitVolume.imperialGallons, UnitVolume.imperialGallons)
probe("UnitVolume.metricCups", UnitVolume.metricCups, UnitVolume.metricCups)
probeType("UnitVolume", UnitVolume.self, UnitVolume.megaliters, UnitVolume.metricCups)

probe("UnitConcentrationMass.millimolesPerLiter(18)", UnitConcentrationMass.millimolesPerLiter(withGramsPerMole: 18), UnitConcentrationMass.millimolesPerLiter(withGramsPerMole: 18))

// --- Unit / Dimension / converter semantics ---
let ua = Unit(symbol: "a"), ua2 = Unit(symbol: "a")
let lin = UnitConverterLinear(coefficient: 1, constant: 2)
let da = Dimension(symbol: "a", converter: lin)
out("unit==unit(same symbol)", ua == ua2)
out("unit.hash==unit.hash(same symbol)", ua.hash == ua2.hash)
out("Set(unit,unit).count", Set([ua, ua2]).count)
out("unit==dimension", ua == da)
out("dimension==unit", da == ua)
out("dimension==dimension(same)", da == Dimension(symbol: "a", converter: UnitConverterLinear(coefficient: 1, constant: 2)))
out("dimension==dimension(other converter)", da == Dimension(symbol: "a", converter: UnitConverterLinear(coefficient: 5)))
out("linear==linear", lin == UnitConverterLinear(coefficient: 1, constant: 2))
out("linear.hash==", lin.hash == UnitConverterLinear(coefficient: 1, constant: 2).hash)
out("UnitConverter().baseUnitValue(3)", UnitConverter().baseUnitValue(fromValue: 3))
out("mpg==imperial mpg", UnitFuelEfficiency.milesPerGallon == UnitFuelEfficiency.milesPerImperialGallon)
out("1 mpg==1 imperial mpg", Measurement(value: 1, unit: UnitFuelEfficiency.milesPerGallon) == Measurement(value: 1, unit: UnitFuelEfficiency.milesPerImperialGallon))
out("tsp==imperial tsp", UnitVolume.teaspoons == UnitVolume.imperialTeaspoons)
out("length.meters==mass.kilograms", (UnitLength.meters as Unit) == (UnitMass.kilograms as Unit))
out("1 m==1 min", Measurement(value: 1, unit: UnitLength.meters) == Measurement(value: 1, unit: UnitDuration.minutes))
out("1 g==1 gravity", Measurement(value: 1, unit: UnitMass.grams) == Measurement(value: 1, unit: UnitAcceleration.gravity))
out("dict[unit]", [UnitLength.meters: 1][UnitLength.meters] as Any)

// --- Non-dimensional Measurement<Unit> ---
let mu = Measurement(value: 2, unit: ua), mu2 = Measurement(value: 2, unit: ua2)
out("Measurement<Unit>==", mu == mu2)
out("Measurement<Unit>.hash==", mu.hashValue == mu2.hashValue)
out("Measurement<Unit>.json", json(mu))
out("Measurement<Unit>+", (mu + mu2).value)
out("Measurement<Unit>.description", "\(mu)")
out("Measurement.debugDescription", String(reflecting: Measurement(value: 1.5, unit: UnitLength.meters)))
out("Measurement.mirror", Mirror(reflecting: Measurement(value: 1.5, unit: UnitLength.meters)).children.map { "\($0.label ?? "-")=\($0.value)" }.joined(separator: ","))

// --- Values that exercise each converted(to:) branch ---
func c<T: Dimension>(_ v: Double, _ a: T, _ b: T) -> Double { Measurement(value: v, unit: a).converted(to: b).value }
out("100 C->F", c(100, UnitTemperature.celsius, .fahrenheit))
out("32 F->C", c(32, UnitTemperature.fahrenheit, .celsius))
out("0 K->C", c(0, UnitTemperature.kelvin, .celsius))
out("-40 F->C", c(-40, UnitTemperature.fahrenheit, .celsius))
out("8 L/100km->mpg", c(8, UnitFuelEfficiency.litersPer100Kilometers, .milesPerGallon))
out("30 mpg->L/100km", c(30, UnitFuelEfficiency.milesPerGallon, .litersPer100Kilometers))
out("30 mpg->imperial mpg", c(30, UnitFuelEfficiency.milesPerGallon, .milesPerImperialGallon))
out("0 L/100km->mpg", c(0, UnitFuelEfficiency.litersPer100Kilometers, .milesPerGallon))
out("0 mpg->L/100km", c(0, UnitFuelEfficiency.milesPerGallon, .litersPer100Kilometers))
out("8 L/100km + 30 mpg", (Measurement(value: 8, unit: UnitFuelEfficiency.litersPer100Kilometers) + Measurement(value: 30, unit: .milesPerGallon)).value)
out("8 L/100km < 30 mpg", Measurement(value: 8, unit: UnitFuelEfficiency.litersPer100Kilometers) < Measurement(value: 30, unit: .milesPerGallon))
out("1 st->lb", c(1, UnitMass.stones, .pounds))
out("1 mi->km", c(1, UnitLength.miles, .kilometers))
out("1 mi->ft", c(1, UnitLength.miles, .feet))
out("1 acre->sq ft", c(1, UnitArea.acres, .squareFeet))
out("1 sq mi->acre", c(1, UnitArea.squareMiles, .acres))
out("1 GB->bits", c(1, UnitInformationStorage.gigabytes, .bits))
out("1 GiB->MB", c(1, UnitInformationStorage.gibibytes, .megabytes))
out("180 deg->rad", c(180, UnitAngle.degrees, .radians))
out("1 rev->deg", c(1, UnitAngle.revolutions, .degrees))
out("3600 arcsec->deg", c(3600, UnitAngle.arcSeconds, .degrees))
out("1 h->min", c(1, UnitDuration.hours, .minutes))
out("1 gal->imperial gal", c(1, UnitVolume.gallons, .imperialGallons))
out("1 cup->fl oz", c(1, UnitVolume.cups, .fluidOunces))
out("1 hp->W", c(1, UnitPower.horsepower, .watts))
out("1 psi->Pa", c(1, UnitPressure.poundsForcePerSquareInch, .newtonsPerMetersSquared))
out("1 kn->km/h", c(1, UnitSpeed.knots, .kilometersPerHour))
out("1 kcal->J", c(1, UnitEnergy.kilocalories, .joules))
out("1 gravity->m/s2", c(1, UnitAcceleration.gravity, .metersPerSecondSquared))
out("1 ly->au", c(1, UnitLength.lightyears, .astronomicalUnits))
out("nan m->km", c(.nan, UnitLength.meters, .kilometers))

