import Foundation
import SwiftMeasurement

struct UnitEntry {
    let name: String
    let dimensions: DimensionalExponents
}

struct Operation {
    let lhs: String
    let symbol: String
    let rhs: String
    let result: String? // nil: dimensionless, returns Double
}

// UnitDispersion is a ratio (scalar * covers it); UnitFuelEfficiency shares UnitArea's exponents.
let units: [UnitEntry] = [
    UnitEntry(name: "UnitAcceleration", dimensions: UnitAcceleration.dimensions),
    UnitEntry(name: "UnitAngle", dimensions: UnitAngle.dimensions),
    UnitEntry(name: "UnitArea", dimensions: UnitArea.dimensions),
    UnitEntry(name: "UnitConcentrationMass", dimensions: UnitConcentrationMass.dimensions),
    UnitEntry(name: "UnitDuration", dimensions: UnitDuration.dimensions),
    UnitEntry(name: "UnitElectricCharge", dimensions: UnitElectricCharge.dimensions),
    UnitEntry(name: "UnitElectricCurrent", dimensions: UnitElectricCurrent.dimensions),
    UnitEntry(name: "UnitElectricPotentialDifference", dimensions: UnitElectricPotentialDifference.dimensions),
    UnitEntry(name: "UnitElectricResistance", dimensions: UnitElectricResistance.dimensions),
    UnitEntry(name: "UnitEnergy", dimensions: UnitEnergy.dimensions),
    UnitEntry(name: "UnitFrequency", dimensions: UnitFrequency.dimensions),
    UnitEntry(name: "UnitIlluminance", dimensions: UnitIlluminance.dimensions),
    UnitEntry(name: "UnitInformationStorage", dimensions: UnitInformationStorage.dimensions),
    UnitEntry(name: "UnitLength", dimensions: UnitLength.dimensions),
    UnitEntry(name: "UnitMass", dimensions: UnitMass.dimensions),
    UnitEntry(name: "UnitPower", dimensions: UnitPower.dimensions),
    UnitEntry(name: "UnitPressure", dimensions: UnitPressure.dimensions),
    UnitEntry(name: "UnitSpeed", dimensions: UnitSpeed.dimensions),
    UnitEntry(name: "UnitTemperature", dimensions: UnitTemperature.dimensions),
    UnitEntry(name: "UnitVolume", dimensions: UnitVolume.dimensions),
]

var operations: [Operation] = []
for lhs in units {
    for rhs in units {
        for symbol in ["*", "/"] {
            if symbol == "/" && lhs.name == rhs.name { continue }
            let exponents = symbol == "*" ? lhs.dimensions + rhs.dimensions : lhs.dimensions - rhs.dimensions
            if exponents.isDimensionless {
                operations.append(Operation(lhs: lhs.name, symbol: symbol, rhs: rhs.name, result: nil))
                continue
            }
            let matches = units.filter { $0.dimensions == exponents }
            if matches.count > 1 {
                let names = matches.map(\.name).joined(separator: ", ")
                FileHandle.standardError.write(Data("error: \(lhs.name) \(symbol) \(rhs.name) matches \(names)\n".utf8))
                exit(1)
            }
            if let match = matches.first {
                operations.append(Operation(lhs: lhs.name, symbol: symbol, rhs: rhs.name, result: match.name))
            }
        }
    }
}

let header = "// Generated by `swift run GenerateTypedAlgebra`. Do not edit.\n"
let verb = ["*": "×", "/": "÷"]

var source = header + """

import Foundation

"""
for operation in operations {
    let returnType = operation.result.map { "Measurement<\($0)>" } ?? "Double"
    let body = operation.result.map {
        "(DimensionalMeasurement(lhs) \(operation.symbol) DimensionalMeasurement(rhs)).convert(to: \($0).self)!"
    } ?? "(DimensionalMeasurement(lhs) \(operation.symbol) DimensionalMeasurement(rhs)).value"
    source += """

/// `\(operation.lhs)` \(verb[operation.symbol]!) `\(operation.rhs)`, \(operation.result == nil ? "as a plain number" : "in the result type's base unit").
public func \(operation.symbol) (lhs: Measurement<\(operation.lhs)>, rhs: Measurement<\(operation.rhs)>) -> \(returnType) {
    \(body)
}

"""
}

var tests = header + """

import Foundation
import Testing
@testable import SwiftMeasurement

@Suite("Typed Algebra (generated)")
struct TypedAlgebraGeneratedTests {

    @Test("Every typed operator agrees with DimensionalMeasurement")
    func agreement() {
"""
for operation in operations {
    tests += """

        do {
            let lhs = Measurement(value: 3.0, unit: \(operation.lhs).baseUnit())
            let rhs = Measurement(value: 2.0, unit: \(operation.rhs).baseUnit())
            let expected = DimensionalMeasurement(lhs) \(operation.symbol) DimensionalMeasurement(rhs)

"""
    if let result = operation.result {
        tests += """
            let typed: Measurement<\(result)> = lhs \(operation.symbol) rhs
            #expect(DimensionalMeasurement(typed) == expected)
        }

"""
    } else {
        tests += """
            let typed: Double = lhs \(operation.symbol) rhs
            #expect(abs(typed - expected.value) < 1e-9)
        }

"""
    }
}
tests += """
    }
}

"""

let root = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
try source.write(
    to: root.appendingPathComponent("Sources/SwiftMeasurement/DimensionalSystem/TypedAlgebra.generated.swift"),
    atomically: true,
    encoding: .utf8
)
try tests.write(
    to: root.appendingPathComponent("Tests/SwiftMeasurementTests/DimensionalSystem/TypedAlgebra.generated.swift"),
    atomically: true,
    encoding: .utf8
)
print("Wrote \(operations.count) operators")
